### ISSUE TITLE
no rrd file generation

### ISSUE THREAD

**Issue by acoul** [manuelkasper/AS-Stats#58]
Greetings,

running as-stats as: ./bin/asstatd.pl -r rrd/ -k conf/knownlinks -P 0

results in no rrd file generation no matter how long the as-stats runs.

as-stats feed has been tested by pmacct either on netflow/v9 or sflow and with softflowd but with no results.

proper netflow/sflow functionality has been successfully tested by wireshark, nfacctd/sfacctd & nfdump

as-stats is disturbingly quiet doing nothing

any ideas suggestions as to how to troubleshoot this would be highly appreciated

**Comment by acoul** [comment]
I am testing as-stats on a fresh 32bit gentoo/rolling system. Just in case of possible issues with a 32bit system, I've also tested this on a fresh 64bit void-linux/rolling musl-libc with the exact same results.

**Comment by JackSlateur** [comment]
Are you sure your configuration is correct ?
If it is not, packets are drop silently, because they do not match your needs (watched host, watched vlan, watched ifindex)

The code is here: https://github.com/manuelkasper/AS-Stats/blob/master/bin/asstatd.pl#L655

**Comment by acoul** [comment]
thank you for the useful feedback. 

commenting out that return on line 655 did not made any difference.

I also tried a previous as-stats v1.5 with no success.

**Comment by acoul** [comment]
I uncommented some print statements on the asstatsd.pl and got the following:

Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
0 => 0 (58 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (58 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (58 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (58 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (58 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (58 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (40 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (60 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (40 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (60 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (450 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (138 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (948 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (1066 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (138 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (40 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (60 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (40 octets, version 4, snmpin 0, snmpout 0)

I forgot to mention that this setup runs on a IP/BGP/AS private 10.0.0.0/8 [AWMN](https://en.wikipedia.org/wiki/Athens_Wireless_Metropolitan_Network) network.

I also commented out [line 628](https://github.com/manuelkasper/AS-Stats/blob/master/bin/asstatd.pl#L628) without any change on this issue.

More information about my setup can be found [here](https://github.com/pmacct/pmacct/issues/113)

**Comment by JackSlateur** [comment]
Can you provide your configuration, as well as a pcap fed with a couple of flow samples ?

**Comment by acoul** [comment]
pmacct/nfprobe config:

daemonize: false
promisc: true
plugin_buffer_size: 10240  
plugin_pipe_size: 10240000
pcap_filter: net 10.0.0.0/8
interface: eth0
plugins: nfprobe
nfprobe_receiver: 10.2.19.18:9000
nfprobe_version:9
nfacctd_net: fallback
nfacctd_as_new: fallback
nfprobe_peer_as: true
sfprobe_peer_as: true
bgp_daemon_pipe_size: 1310710
bgp_daemon: true
bgp_daemon_ip: 10.2.19.4
bgp_daemon_id: 10.2.19.4
bgp_agent_map: /etc/pmacct/agent_to_peer.map
bgp_daemon_port: 17917
bgp_follow_nexthop: 10.2.19.0/24, 10.2.146.0/24, 10.0.0.0/8
aggregate: src_host, dst_host, src_port, dst_port, src_as, dst_as, as_path, peer_src_as, peer_dst_as, proto

/etc/pmacct/agent_to_peer.map : 
bgp_ip=10.2.19.1 ip=10.0.0.0/8
bgp_ip=10.2.19.3 ip=10.0.0.0/8

[nfcapd.zip](https://github.com/manuelkasper/AS-Stats/files/801512/nfcapd.zip)

**Comment by acoul** [comment]
I had some progress:

DEBUG Sampling Rate for 10.2.19.1_0 is IN: 1 | OUT: 1
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Template ID 1024 from 0/10.2.19.1 does not (yet) exist
Updated template ID 1024 (source ID 0, from 10.2.19.1)
Updated template ID 1025 (source ID 0, from 10.2.19.1)
0 => 0 (40 octets, version 4, snmpin 0, snmpout 0)
2493: flushing data for AS 0 (1488059548)
2493: creating RRD file for AS 0
0 => 0 (60 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (40 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (60 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (94 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (78 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (143 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (65 octets, version 4, snmpin 0, snmpout 0)
0 => 0 (139 octets, version 4, snmpin 0, snmpout 0)

my conf/knownlinks : 
10.2.19.1		0				SupperQuagga		SupperQuagga		ABCDEF	1

**Comment by acoul** [comment]
let me shamefully close this "ticket" as invalid, apologizing for the "lost cycles", since as-stats seems to properly doing whatever was designed to do, though quite silently. 

being a n00b on this field, I am still exploring and learning its wonders. You may see some of my efforts [here](http://dev.ozo.com/as-stats/)

thank you dearly for offering such a handy little tool to the open-source community.
