### ISSUE TITLE
commit 104d4c38b7636043ef08f58ec590fa2c0a21a883 broken

### ISSUE THREAD

**Issue by acoul** [manuelkasper/AS-Stats#62]
with commit 104d4c38b7636043ef08f58ec590fa2c0a21a883  I get no graph generation and gibberish on the AS text/description

reverting back to f8fe1b74bfc7d59fb74845095c99f5c607b78904 fixes the problem. I haven't checked the in-between commits.

**Comment by JackSlateur** [comment]
Have you reran rrd-extractstats.pl after update ?

In d6c4c0ff951a6d8bf881177a4fa41245c6acc1dd, the daystatsfile and so on format changed from text to binary (sqlite database)

I guess you are running the old web interface, which tries to handle the sqlite database as a text file

**Comment by acoul** [comment]
Hi jack and thank you for the clarification.

unfortunately, commit  https://github.com/manuelkasper/AS-Stats/commit/d6c4c0ff951a6d8bf881177a4fa41245c6acc1dd breaks also [as-stats-gui
](https://github.com/nidebr/as-stats-gui).

**Comment by acoul** [comment]
closing as invalid
