### ISSUE TITLE
prefix-to-AS resolution feature/enhansment

### ISSUE THREAD

**Issue by acoul** [manuelkasper/AS-Stats#63]
Would it be difficult to implement such a feature?  for example querying a local file with prefixes/ASNs to assign ASNs on orphan IP/prefix.

On our [open/free wireless network](https://en.wikipedia.org/wiki/Athens_Wireless_Metropolitan_Network) we have some mikrotik boxes that don't sent any AS details on their netflow exports and the vendor by looking at their forum [doesn't look](https://forum.mikrotik.com/viewtopic.php?t=37178) too enthusiast on adding such functionality.

**Comment by JackSlateur** [comment]
For sFlow, you can check out my fork of Elisa Jasinska's module: https://github.com/JackSlateur/perl-net-sflow

It can be used gracefully with as-stats
It simply rebuilds  ASN information based on IP addresses

**Comment by JackSlateur** [comment]
@manuelkasper : if you want such feature, I can provides you a patch that implements my module, optionally, for all flows

I don't know if it is relevant for as-stats, so it's up to you to take the decision :)

**Comment by manuelkasper** [comment]
@JackSlateur If you feel like implementing this, then sure, you're welcome! I currently don't have time to devote to AS-Stats myself, and I'm not using it myself anymore (due to no longer working at an ISP), so AS-Stats is pretty much at the mercy of users and contributors, and all I can do is merge pull requests after a very cursory check ;)

**Comment by acoul** [comment]
@manuelkasper  as-stats really helped me to quickly and easily grasp the world of netflows, providing useful and eye-candy graphs. too sad to hear that you will not be able to fuhrer expanded it. it remains a unique and handy tool. thank you.

@JackSlateur thanks for the feedback. such a patch/enhancement would be great for as-stats.

**Comment by adamgent** [comment]
@JackSlateur it'd be great to see a patch for this, or some clear instructions on how to use your module with as-stats

**Comment by JackSlateur** [comment]
Could you test the patched version (https://github.com/JackSlateur/AS-Stats), which support for netflow v5 ?

**Comment by adamgent** [comment]
I only have sFlow available, if that will work then I'm happy to test it for you.

**Comment by JackSlateur** [comment]
For sFlow, I'll have to commit some small code upstream sFlow.pm, as it currently do not push the required data down the stack

**Comment by adamgent** [comment]
I can drop in your forked sFlow.pm to the perl directory if that's all thats needed?

**Comment by acoul** [comment]
@JackSlateur great news, especially for all those poor [MikroTik users](https://wiki.mikrotik.com/wiki/Manual:IP/Traffic_Flow). It may take some time before I report back, but I will.

**Comment by acoul** [comment]
So far, I've placed ip2as.pm under the bin directory as an executable.  I've also placed ip2asn.json under the www directory next to asinfo.txt.  

Are these the correct locations for those two files?

I created a custom ip2asn.json for our wireless/private BGP network with the following command:
`vtysh -c "sh ip bgp" | grep \/ | cut -c 4-20,60-600 | sort | uniq | sed 's/ 0 //g' | sed 's/  / /g' | grep " i" | awk '{printf "\""$1"\": \""$(NF-1)"\", "}'  | sed 's/^/{/' | sed 's/, $/}/'`

each bgp/router in our network contains all AS/prefix information.

and switched the MikroTik routers to NetFlow v5.

**Comment by acoul** [comment]
It does not seem to [work.](http://dev.ozo.com/as-stats/). the working SupperQuagga/ozonet are pmacctd/netflow_v9. the rest are MikroTik/netfllow_v5 routers.

I am attaching the locally generated ip2asn.json file
[ip2asn.zip](https://github.com/manuelkasper/AS-Stats/files/835922/ip2asn.zip)

**Comment by acoul** [comment]
there was a glitch in my local ip2asn.json file script generator. Fixing that glitch, the module works like a charm.

this is the revised vtysh/json script generator:
`vtysh -c "sh ip bgp" | grep \/24 | cut -c 4-20,60-600 | sort | uniq | sed 's/ 0 //g' | sed 's/  / /g' | sed 's/  / /g' | grep " i" | sed 's/ i//g' | awk '{printf "\""$1"\": \""$NF"\", "}' | sed 's/^/{/' | sed 's/, $/}/'`

thank you Jack

**Comment by JackSlateur** [comment]
@adamgent Please checkout my repo, I added the code for sFlow

**Comment by acoul** [comment]
FWIW [sflowtool](http://www.inmon.com/technology/sflowTools.php) can convert sflow to netflow

> The following example shows sflowtool converting sFlow packets into NetFlow and sending the NetFlow 
> packets to a NetFlow collector specified by a host and port.
> sflowtool -c netflow.inmon.com -d 9991 > /dev/null
