### ISSUE TITLE
SQLite table not getting created

### ISSUE THREAD

**Issue by richardhkirkando** [manuelkasper/AS-Stats#68]
Just attempted upgrading an existing install to the latest from this repository.  When running rrd-extractstats.pl, I get a whole lot of this:

DBD::SQLite::db do failed: no such table: stats at /usr/local/www/as-stats/current/bin/rrd-extractstats.pl line 78.

Is there anything I should be doing to initially create this database or table?

**Comment by richardhkirkando** [comment]
Figured this out, was due to sqlite not liking table names from my knownlinks starting with a number.  Tried to play around with the code, but got bored, renamed things, and rrdtool'd my ds's into new names.

May be a worthwhile future fix, but I won't lose any sleep if its a WONTFIX.

**Comment by GizmoV** [comment]
And [-] in tag names it don't like too.

**Comment by falz** [comment]
It looks like the 'create table' syntax just needs quoting. in rrd-extractstats.pl 

this:
```perl
my $query = 'create table stats(asn int';
foreach my $link (@links) {
	$query .= ", ${link}_in int, ${link}_out int, ${link}_v6_in int, ${link}_v6_out int";
}
$query .= ');';
```

should instead be:

```perl
my $query = 'create table stats(\'asn\' int';
foreach my $link (@links) {
        $query .= ", '${link}_in' int, '${link}_out' int, '${link}_v6_in' int, '${link}_v6_out' int";
}
$query .= ');';
```

**Comment by falz** [comment]
..also in func.inc, ticks must be added:

before:
```perl
        foreach($selected_links as $tag){
                $query_links .= "${tag}_in, ${tag}_out, ${tag}_v6_in, ${tag}_v6_out, ";
                $nlinks += 4;
                $query_total .= " + ${tag}_in + ${tag}_out + ${tag}_v6_in + ${tag}_v6_out";
        }
```

after:
```perl
        foreach($selected_links as $tag){
                $query_links .= "'${tag}_in', '${tag}_out', '${tag}_v6_in', '${tag}_v6_out', ";
                $nlinks += 4;
                $query_total .= " + '${tag}_in' + '${tag}_out' + '${tag}_v6_in' + '${tag}_v6_out'";
        }
```

**Comment by falz** [comment]
SQL requires escaping for double quotes. initially tried single quotes but the select statement does not return integers and the totalls do not add up.

see diff for func.inc and rrd-extractstats.pl.

[asstats-diff-escape-sql.diff.txt](https://github.com/manuelkasper/AS-Stats/files/1797252/asstats-diff-escape-sql.diff.txt)
