### ISSUE TITLE
Incorrect Graphs !!

### ISSUE THREAD

**Issue by shahzaibcb** [manuelkasper/AS-Stats#70]
Hi,

I've setup the AS-Stats on dell switch with sflow. However the graphs are showing bandwidth in Kbps while the bandwidth supposed to be in Mbit/s. More than that IN/bytes showing 0. Please have a look :- 

http://prntscr.com/hokjth

Thanks.

**Comment by JackSlateur** [comment]
I bet your sampling rate is not properly configured

Also, please make sure your switch do sample the input trafic

**Comment by shahzaibcb** [comment]
Hi,

Here is the switch settings for Sflow :

**Comment by JackSlateur** [comment]
So, in your as-stats config, you're using 32768 as a sampling rate, right ?

**Comment by shahzaibcb** [comment]
You mean in /opt/AS-Stats/conf/knownlinks ?

I guess the last value was set to '1', means sampling rate was not synchronized?

**Comment by JackSlateur** [comment]
That's it

A value of "1" mean "every real packets are sampled" (which btw consumes a lot of ressources on your networking hardware), which is not the case

Place 32768 there and restart as-stats, you should get proper graphs (for output anyway)

**Comment by shahzaibcb** [comment]
Hi,

Thanks looks like some sensible graph now. There are few questions, please check that below : 

http://prntscr.com/holxxr

**Comment by JackSlateur** [comment]
Yes

This means that, on this period (24H), you outputs ~37GB of ipv4 traffic

**Comment by shahzaibcb** [comment]
Thanks a lot. 

Another question: If i want to monitor another interface from the switch, all i need to do is to add another link in knowlinks config or there are additional settings required ?

**Comment by JackSlateur** [comment]
Yes, just add another line, and restart as-stats

**Comment by shahzaibcb** [comment]
Thanks. Is there a way to aggregate both these links in graph?

**Comment by shahzaibcb** [comment]
Looks like i found it, you just need to check both Links under Legends and it aggregates : 

http://prntscr.com/homize

No doubt its the amazing tool i was trying to find from years to estimate what country / ISP consuming the most bandwidth :)
